baseURL = "https://dalex11.github.io/tres-gatos/"
languageCode = "es"
title = "Tres Gatos"
theme = "PaperMod"

mainSections = ["posts"]

[pagination]
pagerSize = 10

[[menu.main]]
name = "Contáctanos"
url = "/contacto/"
weight = 10

[[menu.main]]
name = "Acerca de nosotros"
url = "/acerca-de-nosotros/"
weight = 20

[params]

defaultTheme = "light"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
DateFormat = "02 Jan 2006 15:04"

[params.homeInfoParams]
Title = "Tres Gatos"
Content = "Noticias, análisis y reportajes."

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/"

[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/"
