baseURL = "https://dalex11.github.io/tres-gatos/"
languageCode = "es"
title = "Tres Gatos"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]

defaultTheme = "light"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

[params.homeInfoParams]
Title = "Tres Gatos"
Content = "Noticias, análisis y reportajes."

[[params.socialIcons]]
name = "github"
url = "https://github.com/TUUSUARIO"